### PR TITLE
Add Core Features: User Authentication, Onboarding, Faculty Management, and UI Enhancements

### PR DESCRIPTION
**Pull request by TheSwastikLokhande**
This push request introduces several core classes for the app's functionality:
- Login and registration flow implemented with User_Login, Login_signUp, and user_Registration.
- Admin-specific login functionality with Admin_login class.
- Faculty management feature added with Faculty_info class.
- Onboarding process via GettingStart and getting_started_fragment classes.
- UI components managed by FragmentStateAdapter, ImageSliderAdapter, and HomePageActivity.
- Helper classes like DBHelper and LoginRepository for data persistence and management.
- Student image handling through Student_image1, Student_image2, and Student_image3.

### CODE REVIEW

**Comment by PGW0808** [comment]
TutionApp/app/src/main/res/layout/activity_getting_start.xml
line no. 13

**Review by PGW0808 — CHANGES_REQUESTED** [review]
Change the red mark code again pull request

**Review by TheSwastikLokhande — COMMENTED** [review]
changes done

**Comment by ArcherInfotechInhouseTraining** [comment]
your code merged

**Pull request merged**
